apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: staging
  name: testing-flask
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: testing-flask
#      sidecar.istio.io/inject: "true"
  template:
    metadata:
      labels:
        app: testing-flask
#        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: testing-flask
        image: andypradityo/myflaskapp:5
        resources:
            limits:
              cpu: "0.5"
              memory: 64M
        ports:
        - containerPort: 5000